width = 100%
height = 20pt
radius = 0
dpi = 100

background = ${colors.crust}
foreground = ${colors.text}
line-size = 4
border-size = 0pt
border-color = #ff252a36
module-margin = 0
padding-left=0pt
padding-right=0pt
separator =" "
separator-foreground = ${colors.transparent}
seperator-background = ${colors.mauve}

cursor-click = pointer
;cursor-scroll = ns-resize
enable-ipc = true
wm-restack = i3

; vim:ft=dosini
