# Common Settings
include-file = common.ini

# Position
bottom = false
monitor = DP-3

# Modules
modules-left = i3
modules-center = backlight pulseaudio 
modules-right = wired-network-linkspeed wired-network-downspeed wired-network-upspeed

; vim:ft=dosini
