

[module/wired-network-connection]
type = internal/network

# Interface
interface = enp4s0
interface-type = wired

#
interval = 1.0
accumulate-stats = false
unknown-as-up = false

# Connected Layout
format-connected = <label-connected>
format-connected-padding = 0
label-connected-foreground = ${colors.green}
label-connected = %{T2}󰈀%{T-}

# Disconnected Layout
format-disconnected = <label-disconnected>
format-disconnected-padding = 0
label-disconnected-foreground = ${colors.red}
label-disconnected = %{T2}󰈀%{T-}

[module/wired-network-linkspeed]
type = internal/network

# Interface
interface = enp4s0
interface-type = wired

#
interval = 1.0
accumulate-stats = false
unknown-as-up = false

# Connected Layout
format-connected = <label-connected>
format-connected-padding = 1
format-connected-prefix = %{T2}󰌷 %{T-}
format-connected-prefix-foreground = ${colors.mauve}
label-connected = "%{T1}%linkspeed%%{T-}"

[module/wired-network-downspeed]
type = internal/network

# Interface
interface = enp4s0
interface-type = wired

#
interval = 1.0
accumulate-stats = false
unknown-as-up = false

# Connected Layout
format-connected = <label-connected>
format-connected-padding = 0
format-connected-prefix = %{T2} %{T-}
format-connected-prefix-foreground = ${colors.red}
label-connected = %{T1}%downspeed%%{T-}

[module/wired-network-upspeed]
type = internal/network

# Interface
interface = enp4s0
interface-type = wired

#
interval = 1.0
accumulate-stats = false
unknown-as-up = false

# Connected Layout
format-connected = <label-connected>
format-connected-padding = 0
format-connected-prefix = %{T2} %{T-}
format-connected-prefix-foreground = ${colors.green}
label-connected = "%{T1}%upspeed%%{T-}"
