# TODO: Implement automatic ssh config block gen/updating
ssh-keygen type platform username:
	ssh-keygen -t {{type}} -C "skye@skyenet-{{shell('hostname')}}" -f ~/.ssh/keys/{{platform}}_{{username}}-{{datetime("%Y%m%d")}}_{{type}}
