# ==================================================================================================================== #
# Global

[global/wm]
margin-bottom = 0
margin-top = 0
fixed-center = true

include-directory = modules
include-file = themes/colors.ini

# ==================================================================================================================== #
# Primary Screen

[bar/top-primary]
include-file = themes/fonts.ini
include-file = bars/top-primary.ini

[bar/bottom-primary]
include-file = themes/fonts.ini
include-file = bars/bottom-primary.ini

# ==================================================================================================================== #
# Secondary Screens

[bar/bottom-secondary-right]
include-file = themes/fonts.ini
include-file = bars/bottom-secondary.ini
monitor = DP-1

[bar/bottom-secondary-left]
include-file = themes/fonts.ini
include-file = bars/bottom-secondary.ini
monitor = HDMI-0

# ==================================================================================================================== #
