return {
    {
        "neo-tree.nvim",
        branch = "v3.x",
        dependencies = {
            "nvim-lua/plenary.nvim",
            "MunifTanjim/nui.nvim",
            "nvim-tree/nvim-web-devicons",
            "nvim-telescope/telescope.nvim",
            "saifulapm/neotree-file-nesting-config",
        },
        lazy = false,
        keys = {
            { "<leader>fe", ":Neotree filesystem toggle<cr>", desc = "Explorer" },
            { "<leader>fb", ":Neotree buffers toggle<cr>", desc = "Buffers" },
            { "<leader>fg", ":Neotree git_status toggle<cr>", desc = "Git Status" },
            { "<leader>fs", ":Neotree search_in_current_dir<cr>", desc = "Search" },
        },
        opts = {
            sources = { "filesystem", "buffers", "git_status" },
            default_component_configs = {
                indent = {
                    with_markers = true,
                    with_expanders = true,
                },
            },
            filesystem = {
                filtered_items = {
                    visible = false,
                    show_hidden_count = false,
                    hide_dotfiles = false,
                    hide_gitignored = false,
                    hide_hidden = false,
                    hide_by_name = {
                        "package-lock.json",
                    },
                    hide_by_pattern = {
                        "*.egg-info",
                    },
                    never_show = {
                        ".git",
                    },
                },
            },
            window = {
                position = "left",
                width = 40,
                mapping_options = {
                    noremap = true,
                    nowait = true,
                },
                mappings = {
                    ["<space>"] = "toggle_node",
                    ["<2-LeftMouse>"] = "open",
                    ["<cr>"] = "open",
                    ["<esc>"] = "cancel",
                    ["P"] = { "toggle_preview", config = { use_float = true } },
                    ["l"] = "focus_preview",
                    ["S"] = "open_split",
                    ["s"] = "open_vsplit",
                    ["t"] = "open_tabnew",
                    ["w"] = "open_with_window_picker",
                    ["C"] = "close_node",
                    ["z"] = "close_all_nodes",
                    ["a"] = {
                        "add",
                        config = {
                            show_path = "none",
                        },
                    },
                    ["A"] = "add_directory",
                    ["d"] = "delete",
                    ["r"] = "rename",
                    ["y"] = "copy_to_clipboard",
                    ["x"] = "cut_to_clipboard",
                    ["p"] = "paste_from_clipboard",
                    ["c"] = "copy",
                    ["m"] = "move",
                    ["q"] = "close_window",
                    ["R"] = "refresh",
                    ["?"] = "show_help",
                    ["<"] = "prev_source",
                    [">"] = "next_source",
                    ["i"] = "show_file_details",
                },
            },
            enable_diagnostics = true,
            enable_git_status = true,
            enable_modified_markers = true,
            enable_refresh = true,
            open_files_do_not_replace_types = { "terminal", "Trouble", "qf", "Outline" },
            sort_case_insensitive = false,
            sorting_strategy = "ascending",
        },
    },
}
